version: "3"
services:
  adonis-app:
    env_file:
      - ./.env
    build:
      context: .
    ports:
      - "3333:3333"
    depends_on:
      - adonis-db
    networks:
      - mynetwork

  adonis-db:
    image: "nouchka/sqlite3:latest"
    stdin_open: true
    tty: true
    networks:
      - mynetwork

  angular-app:
    build:
      context: ../church-plan-task-admin
    ports:
      - "4200:4200"
    depends_on:
      - adonis-app
    networks:
      - mynetwork

networks:
  mynetwork:
